"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$sudo\
$directory\
$git_branch\
$git_state\
$git_status\
${custom.arcadia}\
$nodejs\
$python\
$cmd_duration\
$line_break\
$character"""

[directory]
style = "blue"

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[python]
format = "[$virtualenv]($style) "
style = "bright-black"

[nodejs]
format = "[$symbol($version)]($style) "
style = "green"

[username]
show_always = true
format = "[$user]($style)"
style_user = "bright-black"
style_root = "red bold"

[hostname]
ssh_only = false
format = "[@$hostname]($style) "
style = "bright-black"

[sudo]
disabled = false
format = "[$symbol]($style)"
symbol = "sudo "
style = "red bold"

[custom.arcadia]
command = "~/.config/starship-arc.sh"
when = "arc root 2>/dev/null"
format = "[ $output]($style) "
style = "purple"
ignore_timeout = true
